open-feature/python-sdk-contrib

openfeature/contrib/providers/flagd/web_api_url_factory.py
- Fixes the implementation of `get_path_for` so it works
Fixes #17
=> fix: get_path_for implementation

openfeature/contrib/hooks/README.md, openfeature/contrib/hooks/otel.py, requirements-dev.in, requirements-dev.txt, tests/hooks/test_otel.py
- Implements an OpenTelemetry tracing hook according to the semantic conventions for feature flags.
Implements [#7](https://github.com/open-feature/python-sdk-contrib/issues/7)
=> feat: implement OpenTelemetry traces hook

providers/openfeature-provider-flagd/tests/test_flagd.py
Removes the `setup` function from Flagd tests which was not testing anything useful and was calling the undocumented `get_provider` function. `get_provider` was removed from the SDK API in the latest version.
=> fix: remove setup from flagd tests

.github/workflows/build.yml
- adds pr trigger types
- removes changes to main trigger
This should trigger a CI run for a release PR.
https://github.com/open-feature/python-sdk-contrib/pull/40
=> ci: add pr trigger types

.github/workflows/release.yml
- added the missing `/dist` suffix to point the `pypi` GHA to the correct folder
=> ci: adjust pypi release artifact path

.pre-commit-config.yaml, ruff.toml
Matches https://github.com/open-feature/python-sdk/pull/272
=> chore: update ruff version to 0.2.1 and remove preview flag

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/defaults.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py
Replace `schema` parameter which was a leftover from the previous HTTP-based implementation.
The `tls` parameter now matches what the rest of the provider implementations are using, and maps better to the standard `FLAGD_TLS` environment variable (not implemented yet).
Note: this is technically a breaking change, but I'd venture that no users would currently be affected.
=> feat: replace scheme with tls argument in FlagdProvider constructor

hooks/openfeature-hooks-opentelemetry/README.md
Also add missing markdown references.
=> docs: update OTel hook readme with correct import paths

.pre-commit-config.yaml, hooks/openfeature-hooks-opentelemetry/src/openfeature/contrib/hook/opentelemetry/__init__.py, mypy.ini, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/config.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py
- configuring `mypy` was not fun, because of the `protobuf` generated code 🙈
=> refactor: add mypy and fix typing issues

hooks/openfeature-hooks-opentelemetry/pyproject.toml, hooks/openfeature-hooks-opentelemetry/src/openfeature/contrib/hook/opentelemetry/__init__.py
See https://github.com/open-feature/python-sdk-contrib/pull/72#discussion_r1532819584
=> fix: fix types for hints in OTel TracingHook

README.md
- removes experimental badge from the readme
The Python SDK is at a place where we can build sharable providers and hooks. Removing the label because each artifact is following semantic convention.
=> docs: remove experimental badge

.github/workflows/release.yml, release-please-config.json
- similar to open-feature/python-sdk#340
=> ci: update release please to new GHA

.github/workflows/build.yml
- Restricts codecov to a single python version
This brings the CodeCov config in line with the Python SDK
=> ci: restrict codecov to a single python version

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/in_process.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/custom_ops.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/targeting.py, providers/openfeature-provider-flagd/tests/test_targeting.py
Note: the semver tests are disabled because the python semver lib does not allow `v` prefixes to the version
closes: #92
=> fix(flagd): improve targeting and fix fractional issue(#92)

.gitignore, .release-please-manifest.json, providers/openfeature-provider-flipt/LICENSE, providers/openfeature-provider-flipt/README.md, providers/openfeature-provider-flipt/pyproject.toml, providers/openfeature-provider-flipt/src/openfeature/contrib/provider/flipt/__init__.py, providers/openfeature-provider-flipt/tests/conftest.py, providers/openfeature-provider-flipt/tests/test_provider.py, release-please-config.json
This PR implements the Flipt provider by wrapping around the OFREP Provider and leveraging Flipt's OFREP api
- Should we support passing the namespace in the constructor this way or just leave it up to users to do it themselves via the generic headers_factory (like they would need to for authentication)
Fixes #89 
Unit Tests: From the base of the package run `hatch test`
Local Usage: Go to the base of the new packager (i.e. `provider/openfeature-provider-flipt`), run `pip install -e .`, and then open a python repl with `python3`:
```python
from openfeature import api
from openfeature.contrib.provider.flipt import FliptProvider
api.set_provider(FliptProvider(base_url="<flipt instance>", namespace="<your namespace>"))
client = api.get_client()
client.get_boolean_value("<your feature flag …
```
=> feat: Add Flipt provider

.github/workflows/release.yml
- removes the Python container so the pypi release process works 🤞
=> ci: update release process

.gitmodules, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/grpc.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/in_process.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/file_watcher.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/grpc_watcher.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/sync_metadata_hook.py, providers/openfeature-provider-flagd/tests/e2e/file/conftest.py
This pr adds context value hydration to the in-process evaluator.
This means, that flagd will provide contextual attributes on connection startup which will be used for inprocess evaluation, like defined in the spec.
https://flagd.dev/reference/specifications/providers/#sync-metadata-properties-in-the-evaluation-context
Follow-up:
=> feat(flagd): Context value hydration

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/config.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/grpc_watcher.py
- adds provider_id option
- adds channel_credentials option
- adds default_authority option
- adds documentation
This is similar to recent changes for Go & Java:
- https://github.com/open-feature/java-sdk-contrib/pull/1259
- https://github.com/open-feature/java-sdk-contrib/pull/1260
- https://github.com/open-feature/go-sdk-contrib/pull/626
- https://github.com/open-feature/go-sdk-contrib/pull/638
=> feat(flagd): Add features to customize auth to Sync API servers

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/config.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/grpc_watcher.py
- Adds option which disables GetMetadata call
- https://github.com/open-feature/flagd/issues/1584
`GetMetadata` call was recently added in https://github.com/open-feature/python-sdk-contrib/pull/195. This is potentially breaking for server implementations that don't support metadata. As such, this PR is a temporary stop-gap for such implementations, and it will be removed when metadata is deprecated with the completion of the above issue.
There's no need to implement this in all languages, we'll do it at maintainer discretion according to user need.
This is similar to recently added option in the Java SDK: https://github.com/open-feature/java-sdk-contrib/pull/1267
CC: @toddbaert @aepfli @gruebel
=> chore(flagd): Add sync metadata disabled

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/provider.py
- with version 0.8.1 of the SDK the parameter names are now internally enforced to be `flag_key` for the `resolve_...()` methods
=> fix(flagd): fix parameter name inconsistency with SDK version 0.8.1

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/grpc.py, providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/grpc_watcher.py
Some error codes are not on the stream, e.g., Istio is sending some special ones, and we already implemented the same logic in Java to bypass this issue. see https://github.com/open-feature/java-sdk-contrib/pull/1261
=> fix: add retry policy to grpc calls.

providers/openfeature-provider-flagd/src/openfeature/contrib/provider/flagd/resolvers/process/connector/grpc_watcher.py
We're expecting to enter this error case. Connections are dropping regularly due to different issues. We will restart the connection, hence this is not worthy for an error-log.
=> fix(flagd): reduce loglevel of expected logs
